# Standards: 0.1
---
- name: Fact riot user
  set_fact:
    riot_user: "{{ riot_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - riot

- become: "{{ (riot_user != ansible_user_id) | bool }}"
  become_user: "{{ riot_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: riot
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - riot

    - name: Remove quarantine flag
      register: riot_quarantine
      failed_when: riot_quarantine.rc != 0 and "No such xattr" not in riot_quarantine.stderr
      changed_when: riot_quarantine.rc == 0
      command: xattr -d com.apple.quarantine /Applications/Riot.app
      tags:
        - riot

    - name: Install pidof package
      homebrew:
        name: pidof
      tags:
        - riot

    - name: Check program running
      register: riot_running
      failed_when: False
      changed_when: riot_running.stdout | length > 0 | bool
      command: pidof Riot
      tags:
        - riot

    - name: Fact program running
      set_fact:
        riot_started: "{{ riot_running.stdout_lines | length > 0 | bool }}"
      tags:
        - riot

...
