# Standards: 0.1
---
- name: Kill riot
  command: killall Riot
  register: riot_kill
  failed_when: riot_kill.rc != 0 and "No matching processes belonging to you were found" not in riot_kill.stderr
  become: "{{ (riot_user != ansible_user_id) | bool }}"
  become_user: "{{ riot_user }}"

- name: Start riot
  when: riot_started
  command: open -j /Applications/Riot.app
  become: "{{ (riot_user != ansible_user_id) | bool }}"
  become_user: "{{ riot_user }}"

...
